using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Genesys.WebServicesClient.Resources
{
    public class UserResource
    {
        public IReadOnlyList<DeviceResource> devices;
        public IReadOnlyList<ChannelResource> channels;
        public IReadOnlyList<CallResource> calls;
        public IReadOnlyList<ChatResource> chats;
    }
}

    //"user": {
    //    "id": "57c0012d87ce40e498b75214c239704c",
    //    "userName": "ksippo",
    //    "firstName": "Kristi",
    //    "lastName": "Sippola",
    //    "emailAddress": "ksippo@demosrv.genesyslab.com",
    //    "roles": ["ROLE_ADMIN",
    //    "ROLE_AGENT"],
    //    "enabled": true,
    //    "devices": [{
    //        "id": "7542eb95-8f1c-4b90-bb2a-1b34578a4627",
    //        "deviceState": "Active",
    //        "userState": {
    //            "id": "9430250E-0A1B-421F-B372-F29E69366DED",
    //            "displayName": "Ready",
    //            "state": "Ready"
    //        },
    //        "phoneNumber": "7001",
    //        "description": "",
    //        "e164Number": "7001",
    //        "telephonyNetwork": "Private",
    //        "doNotDisturb": "Off",
    //        "voiceEnvironmentUri": "http://demosrv:8080/api/v2/voice-environments/0f04b6a9-69c4-4f9f-acdc-4f18755107cc",
    //        "capabilities": ["ForwardCallsOn",
    //        "DoNotDisturbOn"],
    //        "channels": ["voice"]
    //    }],
    //    "skills": [{
    //        "id": "1e49b672-d790-450e-a36d-c799bb682abe",
    //        "name": "WFM_Email",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/1e49b672-d790-450e-a36d-c799bb682abe",
    //        "path": "/skills/1e49b672-d790-450e-a36d-c799bb682abe"
    //    },
    //    {
    //        "id": "59f0e51b-a124-4b29-b841-e806cbf880ef",
    //        "name": "Customer_Service",
    //        "level": "11",
    //        "uri": "http://demosrv:8080/api/v2/skills/59f0e51b-a124-4b29-b841-e806cbf880ef",
    //        "path": "/skills/59f0e51b-a124-4b29-b841-e806cbf880ef"
    //    },
    //    {
    //        "id": "6e9a2e91-f2a0-47ef-954d-17cb052562d3",
    //        "name": "WFM_LostLuggage",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/6e9a2e91-f2a0-47ef-954d-17cb052562d3",
    //        "path": "/skills/6e9a2e91-f2a0-47ef-954d-17cb052562d3"
    //    },
    //    {
    //        "id": "723ff34b-5537-483d-b125-99a7fcb09ee0",
    //        "name": "WFM_MileageCredit",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/723ff34b-5537-483d-b125-99a7fcb09ee0",
    //        "path": "/skills/723ff34b-5537-483d-b125-99a7fcb09ee0"
    //    },
    //    {
    //        "id": "8f4eeced-8ec7-4def-b709-5abb965b25f7",
    //        "name": "WFM_Billling",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/8f4eeced-8ec7-4def-b709-5abb965b25f7",
    //        "path": "/skills/8f4eeced-8ec7-4def-b709-5abb965b25f7"
    //    },
    //    {
    //        "id": "a06db23e-402a-4005-b4af-9663add60efe",
    //        "name": "WFM_Chat",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/a06db23e-402a-4005-b4af-9663add60efe",
    //        "path": "/skills/a06db23e-402a-4005-b4af-9663add60efe"
    //    },
    //    {
    //        "id": "b7e67cd2-ec93-46ae-9f08-2d1fcc9ef21a",
    //        "name": "WFM_VacationPackage",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/b7e67cd2-ec93-46ae-9f08-2d1fcc9ef21a",
    //        "path": "/skills/b7e67cd2-ec93-46ae-9f08-2d1fcc9ef21a"
    //    },
    //    {
    //        "id": "bd381f82-153e-4d60-856e-d2649d2491bc",
    //        "name": "WFM_Voice",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/bd381f82-153e-4d60-856e-d2649d2491bc",
    //        "path": "/skills/bd381f82-153e-4d60-856e-d2649d2491bc"
    //    },
    //    {
    //        "id": "c8655b2f-6d5a-41c5-8f2d-fdeead4028d3",
    //        "name": "WFM_Gold",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/c8655b2f-6d5a-41c5-8f2d-fdeead4028d3",
    //        "path": "/skills/c8655b2f-6d5a-41c5-8f2d-fdeead4028d3"
    //    },
    //    {
    //        "id": "fa51d69d-cfcc-4f0e-ace4-2e45af41e0de",
    //        "name": "WFM_Silver",
    //        "level": "8",
    //        "uri": "http://demosrv:8080/api/v2/skills/fa51d69d-cfcc-4f0e-ace4-2e45af41e0de",
    //        "path": "/skills/fa51d69d-cfcc-4f0e-ace4-2e45af41e0de"
    //    }],
    //    "channels": [{
    //        "channel": "chat",
    //        "userState": {
    //            "id": "9430250E-0A1B-421F-B372-F29E69366DED",
    //            "displayName": "Ready",
    //            "state": "Ready"
    //        }
    //    },
    //    {
    //        "channel": "twitter",
    //        "userState": {
    //            "id": "9430250E-0A1B-421F-B372-F29E69366DED",
    //            "displayName": "Ready",
    //            "state": "Ready"
    //        }
    //    }],
    //    "channelStates": [{
    //        "channel": "chat",
    //        "userState": {
    //            "id": "9430250E-0A1B-421F-B372-F29E69366DED",
    //            "displayName": "Ready",
    //            "state": "Ready"
    //        }
    //    },
    //    {
    //        "channel": "twitter",
    //        "userState": {
    //            "id": "9430250E-0A1B-421F-B372-F29E69366DED",
    //            "displayName": "Ready",
    //            "state": "Ready"
    //        }
    //    }],
    //    "interactions": [],
    //    "chats": [{
    //        "state": "JoinFailed",
    //        "userData": {
    //            "IW_EmbeddedBundleUid": "d36b590a-16b3-4212-af6e-409defb7ae6b",
    //            "RRequestedSkillCombination": "",
    //            "LastCalledAgent_EmployeeID": "KSippola",
    //            "RTargetAgentGroup": "?:Customer_Service > 1",
    //            "IW_BundleUid": "b3442e0e-d070-4996-863c-f5f65b0af72a",
    //            "ServiceType": "WebSupport",
    //            "LastName": "",
    //            "RTenant": "Environment",
    //            "RVQID": "TJQ9B30PVL6VLAH1ET3U08BQF800000N",
    //            "IdentifyCreateContact": "3",
    //            "LCA_TimeStamp_chat": "2016-08-16T09:59:05Z",
    //            "EmailAddress": "",
    //            "LastAgent": "",
    //            "RTargetRequested": "?:Customer_Service > 1",
    //            "ChatServerAppName": "Chat_Server",
    //            "ChatServerHost": "demosrv.genesyslab.com",
    //            "CustomerSegment": "",
    //            "RTargetRuleSelected": "",
    //            "RTargetPlaceSelected": "SIP_Server_Place1",
    //            "AccountNumber": "",
    //            "RTargetObjSelDBID": "",
    //            "RTargetAgentSelected": "KSippola",
    //            "PhoneNumber": "",
    //            "ChatServerDBID": "207",
    //            "LastCalledAgent_TimeStamp": "2016-08-16T09:59:05Z",
    //            "RPVQID": "TJQ9B30PVL6VLAH1ET3U08BQF800000N",
    //            "contact_phone_mobile": "",
    //            "CBR-contract_DBIDs": "",
    //            "CBR-IT-path_DBIDs": "",
    //            "CBR-actual_volume": "",
    //            "RRequestedSkills": null,
    //            "RTargetObjectSelected": "?:Customer_Service > 1",
    //            "IW_CaseUid": "122f5d85-a09c-40a6-a87e-1033be3844b1",
    //            "FullName": " ",
    //            "FirstName": "",
    //            "TimeZone": "-420",
    //            "RVQDBID": "371",
    //            "LCA_EmplID_chat": "KSippola",
    //            "RStrategyName": "IXN_Chat Distribution",
    //            "RTargetTypeSelected": "2",
    //            "Subject": "Test",
    //            "max-handle-time-custom": "300",
    //            "ServiceObjective": 0,
    //            "PegAG?:Customer_Service > 1": 20,
    //            "Priority": 90,
    //            "CBR-Interaction_cost": "",
    //            "ChatServerPort": "4800",
    //            "_data_id": "443-e6f76846-1c54-4752-a797-4684b1071ee8",
    //            "ContactId": "000FXaB5RF5008Q1",
    //            "RStrategyDBID": "461"
    //        },
    //        "id": "000G1aBT734P0015",
    //        "receivedDate": "2016-08-16 03:01:21.000-0700",
    //        "suggestedQueueUris": ["http://demosrv:8080/api/v2/queues/613eefbe-5391-4d04-b98c-843dc4e8be86"],
    //        "revelantResponseTemplateGroups": [],
    //        "participants": [],
    //        "chatType": "Inbound",
    //        "capabilities": ["SetInFocus",
    //        "Complete",
    //        "SetDisposition",
    //        "AttachUserData",
    //        "DeleteUserData",
    //        "UpdateUserData"]
    //    }],
    //    "settings": {
    //        "_multimedia": {
    //            "last-media-logged": "[voice]@SIP_Switch"
    //        },
    //        "ga_preferences.dashboard": {
    //            "ezpulse": "4"
    //        },
    //        "htcc": {
    //            "roles": "admin,agent"
    //        },
    //        "ga_preferences.dashboard_ezpulse_2": {
    //            "title": "\"After Call Work Time\"","col":"3","specId":"\"ezpulse:widget.spec\"","layoutId":"541","row":"1","size":"\"1x2\""},"ga_preferences.dashboard_ezpulse_1":{"title":"\"Total TalK Time\"","col":"2","specId":"\"ezpulse:widget.spec\"","layoutId":"536","row":"1","size":"\"1x2\""},"ga_preferences.dashboard_ezpulse_4":{"title":"\"PFS  QueueLoad\"","col":"2","specId":"\"ezpulse:widget.spec\"","layoutId":"714","row":"3","size":"\"1x2\""},"ga_preferences.reporting":{"pageSize":"10000"},"tasks":{"InteractionWorkspace.TeamCommunicator.canUse":"grant","InteractionWorkspace.Voice.canOneStepConference":"grant","InteractionWorkspace.Voice.canUnactivateChannel":"grant","InteractionWorkspace.Voice.canHoldRetrieveCall":"grant","InteractionWorkspace.KPI.canUse":"grant","InteractionWorkspace.Voice.canSendDTMF":"grant","InteractionWorkspace.Voice.canOneStepTransfer":"grant","InteractionWorkspace.Voice.canSetInteractionDisposition":"grant","InteractionWorkspace.Voice.canRejectCall":"grant","InteractionWorkspace.Voice.canAnswerCall":"grant","InteractionWorkspace.Voice.canTwoStepConference":"grant","InteractionWorkspace.ObjectStatistics.canUse":"grant","InteractionWorkspace.TeamCommunicator.canManageFavorites":"grant","InteractionWorkspace.IM.canUnactivateChannel":"grant","InteractionWorkspace.IM.canUse":"grant","InteractionWorkspace.Voice.canAddRemoveVideo":"grant","InteractionWorkspace.IM.canMakeIM":"grant","InteractionWorkspace.Voice.canUse":"grant","InteractionWorkspace.TeamCommunicator.canViewFavorites":"grant","InteractionWorkspace.Contacts.canUse":"grant","InteractionWorkspace.Voice.canForward":"grant","InteractionWorkspace.Voice.canReleaseCall":"grant","InteractionWorkspace.Voice.canTwoStepTransfer":"grant","InteractionWorkspace.IM.canReleaseIM":"grant"},"security":{"SupervisorExtended":"10","Administrator":"1","Supervisor":"1","SupervisorAdhoc":"3"},"ga_preferences.dashboard_ezpulse_3":{"title":"\"All About My Group\"","col":"1","specId":"\"ezpulse:widget.spec\"","layoutId":"551","row":"3","size":"\"1x2\""},"desktop-redial":{"phone-number2":"5115","phone-number3":"4147562561","phone-number0":"5125","phone-number1":"5115@demosrv: 5057","phone-number6":"4162975756","phone-number7":"4198498371","phone-number4":"4130265865","phone-number5":"4152699001","phone-number9":"","phone-number8":"4106046534"},"interaction-workspace-pushed-url":{"http: //www.wikipedia.org":"","http: //www.google.com":"Google"},"interaction-workspace":{"voicemail.access-number":"","voice.prompt-for-end":"false","login.twitter.isselected":"False","interaction.disposition.cache-timeout-delay":"0","intercommunication.voice.single-step-conference-enabled":"Agent,
    //            AgentGroup,
    //            RoutingPoint,
    //            Contact,
    //            TypeDestination,
    //            Skill","email.from-addresses":"","intercommunication.chat.routing-based-actions":"InitTransfer,
    //            OneStepTransfer","expression.phone-number":"^[\\(\\)\\-\\.\\+\\d\\s\\*#]*[0-9]+[\\(\\)\\-\\.\\+\\d\\s\\*#/]*$","login.SIP_Switch.voice.im.1.dn-queue":"","email.quote-char":">","privilege.active-recording.can-monitor-recording":"true","statistics.displayed-statistics":"","contact.multiple-value-attributes":"PhoneNumber,
    //            EmailAddress","history.visibility-details-panel":"Visible","customized.workbin.fax.in-progress.displayed-columns":"MessageType,
    //            From,
    //            Subject,
    //            Received,
    //            To","privilege.voice.can-one-step-transfer":"true","interaction.case-data.frame-color":"#17849D","main-window.height-with-worksheet-opened":"901","customized.workbin.webform.in-progress.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","InteractionVoice.last-information-panel":"MyInteractionSample","contact.history-displayed-columns":"Status,
    //            Subject,
    //            StartDate,
    //            EndDate","outbound.preview.max-simultaneous-preview-record":"-1","interaction.disposition.is-expanded-on-display":"true","interaction-bar.quick-access-modes.<media-type>":"Pinned,
    //            Floating","gadget-statistics.show":"False","privilege.outbound.can-use":"false","privilege.contact.can-use":"true","contact.ucs-interaction.voice.enable-create":"true","teamcommunicator.mainShowByGroup":"True","InteractionVoice.window-location":"32;229;419;460.956666666663","chat.prompt-for-done":"false","privilege.voice.show-monitoring.can-use":"true","contact.ucs-interaction.voice-campaign.enable-create":"false","privilege.voice.can-reject-call":"true","interaction.disposition.folder-name-depth-<n>":"","chat.typing-timeout":"10","gadget-statistics.topmost":"False","privilege.outbound.can-reschedule-before-call":"true","InteractionChat.last-information-panel":"InteractionContainerView","email.html-format":"true","voice.cancel-after-call-work-on-done":"false","facebook.default-queue":"FacebookOutboundQueue","alert.timeout":"10","privilege.voice.can-make-call":"true","teamcommunicator.add-recent-filters.voice":"","contact.size-primary-panel-main-contact":"0;0","InteractionPullPreview.information-panel-width":"580","InteractionPullPreview.show-information-panel":"True","customized.workbin.workitem.draft.displayed-columns":"MessageType,
    //            To,
    //            Subject,
    //            Submitted,
    //            From","privilege.teamcommunicator.can-manage-favorites":"false","InteractionOutboundEmail.show-information-panel":"False","interaction.disposition.use-attached-data":"false","intercommunication.voice.routing-points":"","interaction.toggle-dropdown-pinned-case-layout":"true","contact.size-dialog-merge-contact":"400;450","email.outbound-queue":"","interaction-bar.quick-access-modes.setting.twitter":"Pinned","privilege.workbins.can-use":"true","login.SIP_Switch.im.1.dn-agent-login":"SIPIM1","InteractionPullPreview.window-location":"579;70;507;748.723333333333","login.prompt-place":"false","InteractionVoice.base-panel-width":"401","login.SIP_Switch.im.1.dn-queue":"","privilege.teamlead.can-monitor-voice":"true","standard-response.visibility-details-panel":"Invisible","customized.workbin.email.failed.displayed-columns":"MessageType,
    //            To,
    //            Subject,
    //            Submitted","privilege.contact.can-create-contact":"true","login.voice.prompt-dn-less-phone-number":"false","interaction.disposition.key-name":"DispositionCode","outbound.call-result-values":"Answered,
    //            AnsweringMachine,
    //            Busy,
    //            NoAnswer,
    //            WrongNumber","InteractionVoice.show-information-panel":"False","facebook.auto-answer":"false","chat.client.text-color":"#166FFF","spellchecker.current-dictionary":"HunSpellDic_en-US","standard-response.tree.columns":"Response=0=-1","login.vmail.isselected":"True","privilege.contacts.can-use-contact-myhistory":"false","privilege.contact.can-use-contact-history-notepad":"true","workbin.email.group.displayed-columns":"From,
    //            To,
    //            Subject,
    //            Received","spellchecker-current-dictionary":"HunSpellDic_en-US","facebook.prompt-for-done":"false","contact.displayed-attributes":"Title,
    //            FirstName,
    //            LastName,
    //            PhoneNumber,
    //            EmailAddress","privilege.teamlead.can-monitor-chat":"false","workbin.email.in-progress":"","agent-status.not-ready-reasons":"","customized.workbin.workitem.in-progress.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","privilege.twitter.can-use":"false","workbin.facebook.draft":"","interaction.web-content":"","customized.workbin.fax.in-progress.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","privilege.contact.can-use-contact-history":"true","privilege.outbound.can-mark-do-not-call":"true","InteractionOutboundEmail.window-location":"220;220;509;326","privilege.contact.can-use-interaction-notepad":"true","InteractionIM.information-panel-width":"200","email.signature.line-<n>":"","customized.workbin.email.failed.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135","toast.case-data.format-business-attribute":"","contact.lookup.<media-type>.enable":"true","privilege.voice.can-two-step-conference":"true","contact.directory-displayed-columns":"LastName,
    //            FirstName,
    //            PhoneNumber,
    //            EmailAddress","privilege.outbound.can-set-call-result":"true","contact.directory-search-attributes":"LastName,
    //            FirstName,
    //            PhoneNumber,
    //            EmailAddress","workspace.web-content":"","workbin.facebook.in-progress":"","interaction.case-data.format-business-attribute":"","chat.system.text-color":"#8C8C8C","workbin.facebook.in-progress.displayed-columns":"From,
    //            Subject,
    //            Received","contact.available-directory-page-sizes":"5,
    //            10,
    //            25,
    //            50","login.webform.isselected":"False","intercommunication.email.queue":"","presence.evaluate-presence":"false","InteractionInboundEmail.information-panel-width":"775","login.SIP_Switch.voice.1.dn-isselected":"False","interaction-bar.quick-access-modes.setting.email":"Pinned","voice.floating-interaction-mode.auto-collapse":"false","teamcommunicator.interactionShowMode":"showFavorites","teamcommunicator.corporate-favorites":"","InteractionChat.information-panel-width":"512","login.sms.isselected":"False","interaction.disposition.value-business-attribute":"DispositionCode","InteractionPushPreview.last-information-panel":"MyInteractionSample","privilege.voice.can-forward":"true","intercommunication.chat.queue":"","email.quote-header":"On<date>,
    //            <contact>wrote: ","login.email.isselected":"True","workbin.email.draft":"","interaction.case-data.header-foreground-color":"#FFFFFF","teamcommunicator.interactionSelectorFilter":"ShowAll","email.include-original-text-in-reply":"true","email.signature":"","customized.workbin.email.pull.displayed-columns":"MessageType,
    //            From,
    //            To,
    //            Subject,
    //            Received","spellchecker.personal-dictionary":"","customized.workbin.email.group.header-size-displayed-columns":"30,
    //            100,
    //            100,
    //            150,
    //            135","contact.visibility-second-panel-main-contact":"Visible","case-data.float-separator":".","privilege.contact.can-use-contact-directory":"true","email.max-attachment-size":"0","customized.workbin.email.group.displayed-columns":"MessageType,
    //            From,
    //            To,
    //            Subject,
    //            Received","login.voice.auto-not-ready-reason":"","standard-response.categories":"$All$","agent-status.enabled-actions-by-channel":"Ready,
    //            NotReady,
    //            NotReadyReason,
    //            AfterCallWork,
    //            Dnd,
    //            LogOff","contact.myhistory-displayed-columns":"Status,
    //            Subject,
    //            StartDate,
    //            EndDate","main-window.show-worksheet":"True","intercommunication.email.routing-based-targets":"","privilege.voice.can-release-call":"true","kpi.displayed-kpis":"","workbins.workbin-selected":"VoiceMailWorkbin","login.voice.list-available-queues":"","InteractionOutboundEmail.information-panel-width":"200","InteractionChat.show-information-panel":"False","main-window.window-title":"$Window.Title$","spellchecker-personal-dictionary":"","InteractionWorkItem.show-information-panel":"False","voice.reject.counter-key-name":"","login.webcallback.isselected":"False","email.reply-prefix":"Re: ","login.voice.prompt-queue":"false","application.last-layout":"main-window","main-window.topmost":"False","login.voice.expression.dn-less-phone-number":"","InteractionPushPreview.show-information-panel":"False","gadget.topmost":"False","email.default-queue":"","customized.workbin.webform.in-progress.displayed-columns":"MessageType,
    //            From,
    //            Subject,
    //            Received,
    //            To","workbin.<media-type>.<workbin-nickname>":"","workbin.email.pull":"Email-Pull","gadget.window-location":"59;681","voice.auto-answer":"false","login.SIP_Switch.im.1.dn-isselected":"True","toolbar.window-docked":"False","teamcommunicator.InteractionShowByGroup":"False","contact.size-second-panel-main-contact":"0;0","intercommunication.voice.make-call-caller-id-business-attribute":"","workbin.email.pull.displayed-columns":"From,
    //            To,
    //            Subject,
    //            Received","email.reply-format":"auto","contact.directory-default-mode":"ListView","privilege.contact.can-use-contact-information":"true","customized.workbin.vmail.VoiceMailWorkbin.header-size-displayed-columns":"30,
    //            205,
    //            135","broadcast.preview-timeout":"10","contact.lookup.enable-create-contact":"true","customized.workbin.email.in-progress.displayed-columns":"MessageType,
    //            From,
    //            Subject,
    //            Received,
    //            To","interaction.case-data.content":"History,
    //            CaseData","InteractionInboundEmail.show-information-panel":"False","gadget-statistics.non-scrolling-stats":"CCStat-QWI-Id=8001@SIP_Switch","customized.workbin.workitem.draft.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","login.voice.is-auto-ready":"false","privilege.teamlead.can-use":"true","login.SIP_Switch.voice.1.dn-agent-login":"SIP1","teamcommunicator.recent-max-records":"10","chat.typing-is-enabled":"true","chat.agent.text-color":"#385078","gadget-statistics.window-location":"1071;93","teamcommunicator.max-suggestion-size":"10","InteractionWorkItem.window-location":"28;119;381;551.723333333333","campaign.displayed-columns-widths":"NeuN,
    //            NeuN,
    //            NeuN,
    //            NeuN,
    //            NeuN","privilege.active-recording.can-use":"true","privilege.voice.can-send-dtmf":"true","workbin.twitter.in-progress.displayed-columns":"From,
    //            Subject,
    //            Received","contact.default-directory-page-size":"10","statistics.routing-points":"","system.cometd.timeout":"60000","chat.agent.prompt-color":"#385078","privilege.contact.can-use-save-contact":"true","statistics.refresh-time":"20","workbin.email.group":"agent-group-workbin","contact.lookup.<media-type>.enable-create-contact":"true","gui.theme":"Default","intercommunication.voice.make-call-caller-id-enable-anonymous":"false","InteractionVoice.information-panel-width":"418","chat.pending-response-to-customer":"30,
    //            50","privilege.outbound.can-get-next-preview-record":"true","privilege.voice.can-extend-after-call-work":"false","voice.mark-done-on-release":"false","privilege.contact.can-use-assign-contact":"false","intercommunication.voice.routing-based-actions":"MakeCall,
    //            OneStepConference,
    //            InitConference,
    //            OneStepTransfer,
    //            InitTransfer","statistics.virtual-queues":"","teamcommunicator.request-start-timer":"500","login.SIP_Switch.voice.im.1.dn-agent-login":"SIP1","contact.orientation-main-contact":"Vertical","InteractionInboundEmail.window-location":"82;132;465;421","system.notif.enabled-websocket":"false","facebook.outbound-queue":"FacebookOutboundQueue","customized.workbin.email.draft.displayed-columns":"MessageType,
    //            To,
    //            Subject,
    //            Submitted,
    //            From","InteractionPullPreview.base-panel-width":"495","InteractionPushPreview.window-location":"646;157;429;596.723333333333","privilege.chat.can-consult":"true","workbin.email.in-progress.displayed-columns":"From,
    //            Subject,
    //            Received","kpis.skills.can-use":"true","privilege.voice.can-two-step-transfer":"true","chat.auto-answer":"false","teamcommunicator.show-all-internal-targets":"false","InteractionIM.show-information-panel":"False","login.SIP_Switch.voice.1.dn-queue":"","privilege.voice.can-use":"true","InteractionChat.base-panel-width":"1000","intercommunication.voice.routing-based-targets":"","privilege.chat.can-one-step-transfer":"true","InteractionIM.window-location":"64;352;509;421","intercommunication.email.routing-based-actions":"OneStepTransfer","email.auto-answer":"false","email.prompt-for-done":"false","privilege.outbound.can-reject-record":"true","privilege.voice.can-one-step-conference":"true","login.fax.isselected":"False","login.facebook.isselected":"False","statistics.queue-groups":"","history.details-panel-height":"0,
    //            3","agent-status.enabled-actions-global":"Ready,
    //            NotReady,
    //            NotReadyReason,
    //            AfterCallWork,
    //            Dnd,
    //            LogOff","twitter.auto-answer":"false","InteractionPushPreview.information-panel-width":"728","chat.prompt-for-end":"false","login.workitem.isselected":"False","privilege.email.can-use":"true","chat.time-stamp":"true","teamcommunicator.load-at-startup":"true","privilege.contact.can-delete-contact":"true","toast.case-data.content":"History,
    //            CaseData","workbin.twitter.draft":"","interaction-bar.quick-access-modes":"Pinned,
    //            Floating","toolbar.window-autohide":"False","login.facebooksession.isselected":"True","privilege.facebook.can-use":"false","workbin.twitter.in-progress":"","voicemail.notification-types":"personal,
    //            public","privilege.contact.can-use-contact-history-case-data":"true","InteractionPullPreview.last-information-panel":"InteractionContainerView","workbin.facebook.draft.displayed-columns":"To,
    //            Subject,
    //            Submitted","InteractionWorkItem.information-panel-width":"764","privilege.outbound.can-reschedule":"false","login.voice.dn-less-phone-number.valid-format":"","privilege.contact.can-use-contact-history-detail":"true","login.SIP_Switch.voice.im.1.dn-isselected":"True","customized.workbin.email.pull.header-size-displayed-columns":"30,
    //            100,
    //            100,
    //            150,
    //            135","InteractionPushPreview.base-panel-width":"411","privilege.teamcommunicator.can-use":"true","privilege.teamcommunicator.can-view-favorites":"true","login.list-available-locales":"","application.wiki-help-site":"http: //docs.genesys.com/","login.enable-same-agent-place":"prompt","chat.nickname":"$Agent.UserName$","login.trainingitem.isselected":"True","contact.mandatory-attributes":"FirstName,
    //            LastName","login.chat.isselected":"True","interaction-bar.quick-access-modes.setting.chat":"Pinned","customized.workbin.vmail.in-progress.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","facebook.comments-pagination-size":"2","privilege.teamcommunicator.can-view-recent-calls":"true","customized.workbin.email.draft.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","interaction.disposition.is-read-only-on-idle":"false","interaction.override-option-key":"","teamcommunicator.voice.list-status-reachable":"Unavailable","chat.client.prompt-color":"#166FFF","workbin.twitter.draft.displayed-columns":"To,
    //            Subject,
    //            Submitted","privilege.outbound.can-cancel-record":"true","statistics.agent-groups":"","InteractionInboundEmail.last-information-panel":"MyInteractionSample","customized.workbin.vmail.VoiceMailWorkbin.displayed-columns":"MessageType,
    //            Subject,
    //            Received","contact.lookup.enable":"true","privilege.chat.can-use":"true","gui.editor-zoom":"100","privilege.teamcommunicator.can-view-all":"true","interaction.disposition.is-mandatory":"false","InteractionInboundEmail.base-panel-width":"1000","customized.workbin.email.in-progress.header-size-displayed-columns":"30,
    //            100,
    //            150,
    //            135,
    //            100","privilege.chat.can-one-step-conference":"true","voicemail.request-timeout":"1","privilege.voicemail.can-use":"false","teamcommunicator.max-size":"50","teamlead.monitoring-scope":"call","workbin.email.draft.displayed-columns":"To,
    //            Subject,
    //            Submitted","outbound.call-result-automatically-selected":"","teamcommunicator.mainShowMode":"showFavorites","privilege.outbound.can-dial-alternative-chained-record":"true","expression.phone-number.supported-characters":"0123456789+","intercommunication.chat.routing-based-targets":"","privilege.SRL.can-use":"true","teamcommunicator.always-clear-textbox-on-new-interaction":"true","email.max-attachments-size":"0","toolbar.window-location":"566;0;1024;901;0","teamcommunicator.list-filter-showing":"Agent,
    //            AgentGroup,
    //            RoutingPoint,
    //            Skill,
    //            InteractionQueue,
    //            Contact,
    //            CustomContact","login.SIP_Switch.voice.1.dn-sip-phone-number":"7001","customized.workbin.workitem.in-progress.displayed-columns":"MessageType,
    //            From,
    //            Subject,
    //            Received,
    //            To","interaction.case-data.is-read-only-on-idle":"true","InteractionWorkItem.base-panel-width":"1000","chat.enable-auto-disconnect":"true","main-window.last-worksheet-view":"MyWorkplaceContainerView","InteractionWorkItem.last-information-panel":"MyInteractionSample","teamcommunicator.mainSelectorFilter":"Agent","InteractionIM.base-panel-width":"491","InteractionChat.window-location":"60;215;500;591","workbin.<media-type>.<workbin-nickname>.displayed-columns":"From,
    //            To,
    //            Subject,
    //            Received","campaign.displayed-columns":"State,
    //            Name,
    //            DeliveryMode,
    //            Date,
    //            Description","privilege.email.can-add-attachment":"true","InteractionOutboundEmail.base-panel-width":"497","privilege.outbound.can-reschedule-on-new-number":"true","history.list-panel-height":"0,
    //            69","customized.workbin.vmail.in-progress.displayed-columns":"MessageType,
    //            From,
    //            Subject,
    //            Received,
    //            To"},"interaction-workspace-recent":{"Agentbtamzari":"{
    //                \\\"type\\\":\\\"Agent\\\",\\\"userName\\\":\\\"btamzari\\\",\\\"recentInformation\\\":{\\\"media\\\":\\\"voice\\\",\\\"direction\\\":\\\"OUT\\\",\\\"type\\\":\\\"Outbound\\\",\\\"isConsultation\\\":false,\\\"timeStamp\\\":1434648853327}}"
    //            },
    //            "interaction-workspace-recents": {
    //                "cfgPerson119": "[B@704b3229",
    //                "customcontact7C8438BF835F087AC742472BAC87EC89DE36AB6F": "[B@b7583f",
    //                "customcontact87DAE8422BE9A63B0881BBF0766782801F522B34": "[B@5029077",
    //                "customcontact89BCF37F382C700090E127AB1012861F48F7F1AB": "[B@6b5a7732",
    //                "customcontact19DD466E43CDBD3833ABC0609EBA6D8786F9B342": "[B@672e0e75",
    //                "customcontact14ADB09B00D8C6F7D9BCF9E523DCD613A9078393": "[B@45999985",
    //                "customcontact0F1E2197856E1064901A7B3AE56EA03820673649": "[B@4d32da4b",
    //                "cfgPerson118": "[B@69172c05",
    //                "cfgAgentGroup178": "[B@7c84a798",
    //                "contactucs0001Ea5T2RFT001K": "[B@58ca5b57"
    //            },
    //            "multimedia": {
    //                "last-media-logged": "email,chat,workitem,twitter"
    //            },
    //            "ga_preferences.dashboard_ezpulse_0": {
    //                "title": "\"Calls Served\"","col":"1","specId":"\"ezpulse:widget.spec\"","layoutId":"528","row":"1","size":"\"1x2\""},"interaction-workspace-favorites":{"cfgPerson119":"[B@372692d7","cfgPerson120":"[B@45727d8a","cfgPerson121":"[B@5f9012a4","cfgPerson301":"[B@6bb7fdff","cfgPerson118":"[B@964c68a"},"TServer":{"gvm_mailbox":"7777"}},"calls":[],"changePasswordOnFirstLogin":false,"groups":[{"id":"2-36d89841-d1a8-4e92-a6bd-263f042dfdb7","name":"SampleGroup","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-36d89841-d1a8-4e92-a6bd-263f042dfdb7","path":"/groups/2-36d89841-d1a8-4e92-a6bd-263f042dfdb7"},{"id":"2-d5f4c955-3ac4-4f21-95fe-f2aface972b0","name":"SIPGroup","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-d5f4c955-3ac4-4f21-95fe-f2aface972b0","path":"/groups/2-d5f4c955-3ac4-4f21-95fe-f2aface972b0"},{"id":"2-089c9485-2581-430c-abb6-40a0c4c87faf","name":"OpenMedia","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-089c9485-2581-430c-abb6-40a0c4c87faf","path":"/groups/2-089c9485-2581-430c-abb6-40a0c4c87faf"},{"id":"2-bc9b97b6-9fad-42ab-aa48-ab8be9262940","name":"ProactiveRecording","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-bc9b97b6-9fad-42ab-aa48-ab8be9262940","path":"/groups/2-bc9b97b6-9fad-42ab-aa48-ab8be9262940"},{"id":"2-5b6c99ff-179a-4d35-8dc4-d9c1c35497b5","name":"Customer_Service","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-5b6c99ff-179a-4d35-8dc4-d9c1c35497b5","path":"/groups/2-5b6c99ff-179a-4d35-8dc4-d9c1c35497b5"},{"id":"2-b08d8efa-8dfa-4e05-a3fe-19706dd9061b","name":"Savings","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-b08d8efa-8dfa-4e05-a3fe-19706dd9061b","path":"/groups/2-b08d8efa-8dfa-4e05-a3fe-19706dd9061b"},{"id":"2-748e4d75-7704-4994-a4d7-e8e84f4e65d6","name":"WebCallbackdistributionforprocessing","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-748e4d75-7704-4994-a4d7-e8e84f4e65d6","path":"/groups/2-748e4d75-7704-4994-a4d7-e8e84f4e65d6"},{"id":"2-91284a08-815d-47e9-81be-fb0b09f1c8a5","name":"All_Standard_Agents","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-91284a08-815d-47e9-81be-fb0b09f1c8a5","path":"/groups/2-91284a08-815d-47e9-81be-fb0b09f1c8a5"},{"id":"2-d7766d30-91b3-4ceb-a797-dbb4192bb971","name":"Service","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-d7766d30-91b3-4ceb-a797-dbb4192bb971","path":"/groups/2-d7766d30-91b3-4ceb-a797-dbb4192bb971"},{"id":"2-cd5d32ab-80e5-4a6e-a53f-d6b25f89f95b","name":"All_Platinum_Agents","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-cd5d32ab-80e5-4a6e-a53f-d6b25f89f95b","path":"/groups/2-cd5d32ab-80e5-4a6e-a53f-d6b25f89f95b"},{"id":"2-871fdae8-c01b-4653-ae5c-1fc06a694e75","name":"Sales","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-871fdae8-c01b-4653-ae5c-1fc06a694e75","path":"/groups/2-871fdae8-c01b-4653-ae5c-1fc06a694e75"},{"id":"2-ec9c7e0e-80f4-4157-bc52-f3b8552c0a93","name":"WebEngagementVoice","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-ec9c7e0e-80f4-4157-bc52-f3b8552c0a93","path":"/groups/2-ec9c7e0e-80f4-4157-bc52-f3b8552c0a93"},{"id":"2-9953ebb4-60da-4306-b6b3-8dfc0ed89371","name":"GroupInUnit","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-9953ebb4-60da-4306-b6b3-8dfc0ed89371","path":"/groups/2-9953ebb4-60da-4306-b6b3-8dfc0ed89371"},{"id":"2-803c0c8e-bd02-46c8-bc61-28f89552bb56","name":"All_Premium_Agents","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-803c0c8e-bd02-46c8-bc61-28f89552bb56","path":"/groups/2-803c0c8e-bd02-46c8-bc61-28f89552bb56"},{"id":"2-6cec5479-f6d0-4742-8724-169b416b21b6","name":"VMGroup","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-6cec5479-f6d0-4742-8724-169b416b21b6","path":"/groups/2-6cec5479-f6d0-4742-8724-169b416b21b6"},{"id":"2-802dd4c7-e4be-4c2d-970d-853b66b52cf3","name":"SocialMediaAgentGroup","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-802dd4c7-e4be-4c2d-970d-853b66b52cf3","path":"/groups/2-802dd4c7-e4be-4c2d-970d-853b66b52cf3"},{"id":"2-03a290dc-37b0-4a9f-8855-bfd54093c7e8","name":"Billing","type":"BusinessUnit","contains":["users","skills","queues"],"uri":"http: //demosrv: 8080/api/v2/groups/2-03a290dc-37b0-4a9f-8855-bfd54093c7e8","path":"/groups/2-03a290dc-37b0-4a9f-8855-bfd54093c7e8"}],"features":[{"id":"api-provisioning-write","displayName":"APIProvisioningWrite","description":"Generalprovisioningwrite","uri":"http: //demosrv: 8080/api/v2/features/api-provisioning-write","path":"/features/api-provisioning-write"},{"id":"ui-supervisor-reporting","displayName":"UISupervisorReporting","description":"UIforReportingSupervisor","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-reporting","path":"/features/ui-supervisor-reporting"},{"id":"api-platform-configuration-read","displayName":"PlatformConfigurationAPI-read","description":"Low-levelconfigurationAPI","uri":"http: //demosrv: 8080/api/v2/features/api-platform-configuration-read","path":"/features/api-platform-configuration-read"},{"id":"ui-supervisor-recording","displayName":"UISupervisorRecording","description":"UIforCallRecordingSupervisor","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-recording","path":"/features/ui-supervisor-recording"},{"id":"api-provisioning-read","displayName":"APIProvisioningRead","description":"Generalprovisioningread","uri":"http: //demosrv: 8080/api/v2/features/api-provisioning-read","path":"/features/api-provisioning-read"},{"id":"api-voice","displayName":"VoiceAPI","description":"APIforVoice","uri":"http: //demosrv: 8080/api/v2/features/api-voice","path":"/features/api-voice"},{"id":"api-agent-control","displayName":"Agentstatecontrol","description":"api-agent-control","uri":"http: //demosrv: 8080/api/v2/features/api-agent-control","path":"/features/api-agent-control"},{"id":"api-supervisor-recording","displayName":"APISupervisorRecording","description":"APIforCallRecordingSupervisor","uri":"http: //demosrv: 8080/api/v2/features/api-supervisor-recording","path":"/features/api-supervisor-recording"},{"id":"ui-supervisor-provisioning-user","displayName":"UISupervisorProvisioningUser","description":"UISupervisorProvisioningUser","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-provisioning-user","path":"/features/ui-supervisor-provisioning-user"},{"id":"ui-supervisor-provisioning-routing","displayName":"UISupervisorProvisioningforRouting","description":"RoutingProvisioningUI","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-provisioning-routing","path":"/features/ui-supervisor-provisioning-routing"},{"id":"api-multimedia","displayName":"MultimediaAPI","description":"APIforMultimedia","uri":"http: //demosrv: 8080/api/v2/features/api-multimedia","path":"/features/api-multimedia"},{"id":"api-multimedia-email","displayName":"MultimediaEmailAPI","description":"APIforMultimediaEmail","uri":"http: //demosrv: 8080/api/v2/features/api-multimedia-email","path":"/features/api-multimedia-email"},{"id":"ui-supervisor-edit-user","displayName":"UISupervisorEditUser","description":"UIforSupervisorstoEditUsers","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-edit-user","path":"/features/ui-supervisor-edit-user"},{"id":"api-supervisor-agent-control","displayName":"APISupervisorAgentControl","description":"APIforSupervisorstoControlAgentState","uri":"http: //demosrv: 8080/api/v2/features/api-supervisor-agent-control","path":"/features/api-supervisor-agent-control"},{"id":"api-supervisor-monitoring","displayName":"APISupervisorMonitoring","description":"APIforSupervisorstoMonitorAgents","uri":"http: //demosrv: 8080/api/v2/features/api-supervisor-monitoring","path":"/features/api-supervisor-monitoring"},{"id":"ui-supervisor-cc-segmentation","displayName":"UISupervisorCCSegmentation","description":"Whenassigned,
    //                SupervisorUIwillprovideContactCenterSegmentation","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-cc-segmentation","path":"/features/ui-supervisor-cc-segmentation"},{"id":"api-multimedia-chat","displayName":"MultimediaChatAPI","description":"APIforMultimediaChat","uri":"http: //demosrv: 8080/api/v2/features/api-multimedia-chat","path":"/features/api-multimedia-chat"},{"id":"api-platform-configuration-write","displayName":"PlatformConfigurationAPI-write","description":"Low-levelconfigurationAPI","uri":"http: //demosrv: 8080/api/v2/features/api-platform-configuration-write","path":"/features/api-platform-configuration-write"},{"id":"ui-supervisor-provisioning-skill","displayName":"UISupervisorSkillProvisioning","description":"UISupervisorSkillProvisioning","uri":"http: //demosrv: 8080/api/v2/features/ui-supervisor-provisioning-skill","path":"/features/ui-supervisor-provisioning-skill"},{"id":"api-multimedia-twitter","displayName":"MultimediaTwitterAPI","description":"APIforMultimediaTwitter","uri":"http: //demosrv: 8080/api/v2/features/api-multimedia-twitter","path":"/features/api-multimedia-twitter"}],"uri":"http: //demosrv: 8080/api/v2/users/57c0012d87ce40e498b75214c239704c","path":"/users/57c0012d87ce40e498b75214c239704c"}}
